Add item requests
Ruslan-Bulatovich/java-shareit pull request #5
Opened 2023-05-20 19:05 UTC by Ruslan-Bulatovich

2023-05-22 19:28 UTC, alexache requested changes
Необходимы еще юнит тесты на сервисы и репозитории с кастомными запросами (ItemRepository содержит такой метод)

2023-05-22 19:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode
На моделях для JPA нельзя использовать генерированные ломбоком equals/hashcode, и в целом тема правильного написания этих методов не очень проста

2023-05-22 19:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
Такие исключения, в которых уже закладываются статусы ответа HTTP не очень хороши по одной простой причине - смешивание слоев. Получается, что сервис уже решает, что будет отвечать контроллер, что неправильно. Лучше использовать RestControllerAdvice, чтобы связывать исключения и коды ответов

2023-05-22 19:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +        return getClass().hashCode();
Некорректный метод хэшкода для JPA модели

2023-05-22 19:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    private final String userIdHeader = "X-Sharer-User-Id";
Можно константы делать еще и static (так принято)

2023-05-22 19:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private static BookingDto bookingDto;
Зачем эти поля статик и пересоздаются в @SetUp?

2023-05-22 19:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    }
Хорошо бы еще добавить verify на количество вызовов createBooking

2023-05-22 19:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        bookingDto.setStart(LocalDateTime.now().plusDays(1));
Для чего это, если обхекты пересоздаются на каждый тестовый метод?

2023-05-22 19:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/Bookings.java
> +public abstract class Bookings {
Для чего этот класс?

2023-05-22 19:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        Thread.sleep(50);
Тесты со слипами - это очень плохо и долго

2023-05-22 19:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +public class BookingServiceTest extends Bookings {
Выглядит больше как интеграционный тест, тогда не хватает юнит теста на сам сервис

2023-05-22 19:28 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +        lastBooking = new Booking();
Какая-то немного не очевидная работа с этими полями класса

2023-05-25 14:28 UTC, Ruslan-Bulatovich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode
убрал аннотации

2023-05-25 14:28 UTC, Ruslan-Bulatovich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
Исправил, статусы HHTP теперь в RestControllerAdvice

2023-05-25 14:28 UTC, Ruslan-Bulatovich commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    private final String userIdHeader = "X-Sharer-User-Id";
исправил

2023-05-25 14:28 UTC, Ruslan-Bulatovich commented on src/test/java/ru/practicum/shareit/booking/Bookings.java
> +public abstract class Bookings {
Лишний, исправил

2023-05-25 14:28 UTC, Ruslan-Bulatovich commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        Thread.sleep(50);
Понял

2023-05-25 14:30 UTC, Ruslan-Bulatovich commented
Привет, добавил тесты для itemrepository и поправил ошибки!

2023-05-26 10:17 UTC, Ruslan-Bulatovich commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +        lastBooking = new Booking();
По идее я мог воспользоваться маппером и преобразовать ItemDtoResponse  в Item, но не хотел добавлять еще и маппер в зависимость

2023-05-26 16:18 UTC, alexache requested changes

2023-05-26 16:18 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/User.java
>  @Data
В прошлую итерацию пропустил момент, что у этого класса есть аннотация @Data, которая включает в себя @EqualsAndHashCode, а значит нельзя применять к JPA модели

2023-05-26 16:27 UTC, Ruslan-Bulatovich commented on src/main/java/ru/practicum/shareit/user/model/User.java
>  @Data
Привет! По тестам сервиса понял. По репозиториям не нужно же писать тесты? Где был кастомный запрос я написал. Более ты не просил да и дедлайн горит)

2023-05-26 16:48 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/User.java
>  @Data
С репозиторием все ок, нужен был только один тест

2023-05-27 22:30 UTC, Ruslan-Bulatovich commented
Привет! Я добавил юнит тесты BookingServiceImplTest, убрал Thread.sleep(50). Интеграционные тесты с добавлением контроллером у меня к сожалению не получились. За то поправил тесты букингов, было много недочетов!

2023-05-28 07:08 UTC, alexache approved these changes

2023-05-28 07:08 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
А что поменялось? Не вижу мока репозитория, должно быть чем то похоже на тест контроллера, где у сервиса мок

2023-05-28 16:20 UTC, merged